# GitHub Sponsors funding options
github: [NoritakaIkeda]

# Other funding platforms (uncomment and update as needed)
# patreon: username
# open_collective: coverage-runner
# ko_fi: username
# tidelift: npm/coverage-runner
# community_bridge: coverage-runner
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: coverage-runner

# Custom funding URLs
custom: []

# Funding message (optional)
# This appears on the repository's main page
# Consider adding a brief message about how funding helps the project